### PR TITLE
Bumped Halide version, added Python bindings

### PR DESCRIPTION
**Pull request by csachs**
Given conda originating from the Python ecosystem I was somewhat puzzled to see the Python bindings of Halide not being built.

I've bumped Halide to the current version, and added the necessary changes to build and install Halide's Python bindings.

I've only tested it on Linux (w/Python 3); I'll check what Travis reports for macOS or Python 2.

Best regards, Christian

### CODE REVIEW

**Comment by isuruf** [comment]
If the python bindings of a package can be built separately, we usually make it a separate conda package

**Comment by cassianokc** [comment]
Hi, what is missing for this one being merged?

Best regards,

**Comment by steven-johnson** [comment]
FYI: the Python Bindings have been ~completely rewritten since this PR was opened (using PyBind11 instead of Boost), and as a result, the build process is slightly different now. 

I'll open a PR to hopefully add this functionality vs. the 2018-02-15 release after https://github.com/conda-forge/halide-feedstock/pull/4 lands.

**Comment by isuruf** [comment]
python bindings are in a different conda package. `halide-python`.

**Pull request closed without merging**
