### PR TITLE
Update to 18

### PR DESCRIPTION
**Pull request by isuruf**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by isuruf** [comment]
@conda-forge-admin rerender

**Comment by isuruf** [comment]
@conda-forge/halide, this is ready for a review. I've added myself as a maintainer to help with the maintenance in the future.

**Comment by minrk** [comment]
Thanks @isuruf! Since it's been so many years since we updated, do you think there's a possibility of doing something about the old CalVer versions instead of bumping the epoch (such as bumping them to a label or repodata patching a feature)? In practice, I don't think anybody really understands how to install projects with version epochs.

**Comment by minrk** [comment]
That sounds like a good solution to me.

**Comment by isuruf** [comment]
I have moved existing `halide` and `halide_python` builds to `halide_calver` label. This is ready for review now.

**Comment by minrk** [comment]
Thanks!

**Pull request merged**
